---
name: Build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:21
          apps: sbt
      - name: Execute tests
        shell: bash
        run: |
          sbt +test
      - name: Verify assembly
        shell: bash
        run: |
          sbt +package +assembly
      - uses: actions/upload-artifact@v4
        with:
          name: jar binaries
          path: |
            spot/target/spark-3.?-jvm-2.1?/spot-*.jar
            spot-complete/target/spark-3.?-jvm-2.1?/spot-complete-*.jar
          retention-days: 7
